name: satbucket
channels: [conda-forge]
dependencies:
  - gpm-api
  - dask
  - pyyaml
  - distributed
  - jupyter
  - numpy
  - polars
  - pyarrow
  - pyproj
  - pytest
  - pytest-cov
  - pytest-mock
  - pytest-sugar
  - trollsift
  - xarray
