name: build-doc-satbucket
channels: [conda-forge]
dependencies:
  - docutils
  - gpm-api
  - jupyter
  - nbsphinx==0.9.3
  - pandoc
  - pip
  - python>=3.10
  - sphinx-book-theme==1.1.0
  - sphinx-gallery
  - sphinx-mdinclude==0.5.3
  - sphinx==7.2.6
  - sphinxcontrib-youtube
  - pip:
      - git+https://github.com/ghiggi/sat-bucket.git
